DROP TABLE TRACKINGSHIPMENTS CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENTS CASCADE CONSTRAINTS;
DROP TABLE packeges CASCADE CONSTRAINTS;
DROP TABLE WORKERS CASCADE CONSTRAINTS;
DROP TABLE STREET CASCADE CONSTRAINTS;
DROP TABLE COSTUMER CASCADE CONSTRAINTS;
DROP TABLE ORDERSTATUS CASCADE CONSTRAINTS;
DROP TABLE CITY CASCADE CONSTRAINTS;
DROP TABLE JOB CASCADE CONSTRAINTS;

