insert into city (cityNum, cityName) values (1, 'Cambrai');
insert into city (cityNum, cityName) values (2, 'Mūsa Khel Bāzār');
insert into city (cityNum, cityName) values (3, 'Taytay');
insert into city (cityNum, cityName) values (4, 'Kutao');
insert into city (cityNum, cityName) values (5, 'Ōmuta');
insert into city (cityNum, cityName) values (6, 'Nong Muang Khai');
insert into city (cityNum, cityName) values (7, 'Ar Ramthā');
insert into city (cityNum, cityName) values (8, 'Seattle');
insert into city (cityNum, cityName) values (9, 'Paris 03');
insert into city (cityNum, cityName) values (10, '''s-Hertogenbosch');
insert into city (cityNum, cityName) values (11, 'Shitang');
insert into city (cityNum, cityName) values (12, 'Shushi');
insert into city (cityNum, cityName) values (13, 'Gongming');
insert into city (cityNum, cityName) values (14, 'Uluarang');
insert into city (cityNum, cityName) values (15, 'Lucija');
insert into city (cityNum, cityName) values (16, 'Duvergé');
insert into city (cityNum, cityName) values (17, 'Ndungu');
insert into city (cityNum, cityName) values (18, 'Likhoy');
insert into city (cityNum, cityName) values (19, 'Wanzhi');
insert into city (cityNum, cityName) values (20, 'Luče');
